# Generated by Django 5.2.7 on 2026-09-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_activitylog_id_alter_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('web_application', 'Web Application'), ('network', 'Network'), ('physical_security', 'Physical Security'), ('social_engineering', 'Social Engineering'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='report',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
    ]
