"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The fallback exists so a fresh clone runs without setup; it is a
# throwaway development value and must be overridden via the environment
# in any deployment. See .env.example.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-only-key-override-me-in-production',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes')

ALLOWED_HOSTS = os.environ.get(
    'DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1',
).split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'accounts',
    'reports',
    'dashboard',
    'common',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Both settings below hard-require a scheme (http:// or https://) on every
# entry - Django's system checks reject any that lack one, and those
# checks run on every management command including `migrate`, so a bare
# domain here would crash the container before it ever starts serving
# (indistinguishable from the outside from a generic "Bad Gateway").
# Silently dropping malformed entries trades a confusing crash-loop for a
# working server that's simply missing one origin - filed as a config
# mistake to fix, not a reason to take the whole app down.
def _valid_origins(env_var, default=''):
    origins = os.environ.get(env_var, default).split(',')
    return [o for o in (origin.strip() for origin in origins) if o.startswith(('http://', 'https://'))]


CORS_ALLOWED_ORIGINS = _valid_origins('CORS_ALLOWED_ORIGINS', 'http://localhost:3000')

# Only needed for Django admin's session-cookie login over HTTPS behind a
# reverse proxy (Traefik/Dokploy) - the JWT-authenticated API itself is
# stateless and unaffected by CSRF.
CSRF_TRUSTED_ORIGINS = _valid_origins('CSRF_TRUSTED_ORIGINS')

# Dokploy/Traefik terminates TLS and forwards plain HTTP, so Django must be
# told to trust the X-Forwarded-Proto header instead of checking the
# connection scheme itself - otherwise request.is_secure() is always False
# and secure-cookie/redirect settings below would misbehave.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

AUTH_USER_MODEL = 'accounts.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Falls back to local SQLite when DATABASE_URL is unset (dev, tests);
# deployments set DATABASE_URL to Dokploy's managed Postgres instance.
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/
# Served by WhiteNoise directly from the app container - this API has no
# real frontend of its own, so this only covers the Django admin's assets.

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    # Defining STORAGES at all replaces Django's built-in defaults
    # entirely, not just the key(s) listed - omitting 'default' here left
    # FileField with no storage backend configured at all, which only
    # surfaced once something (report attachments) actually used one.
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# User-uploaded report attachments. Written to local disk inside the
# container - fine for this app's scale, but note that a Dokploy
# redeploy replaces the container filesystem, so this directory needs a
# persistent volume mounted at MEDIA_ROOT in production or attachments
# won't survive a redeploy. Swapping to S3-compatible storage later only
# means changing STORAGES['default'], not any application code.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
